#!/bin/bash
### BEGIN INIT INFO
# Provides:          supervisord
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: supervisord
# Description:
#
### END INIT INFO

# Supervisord auto-start for Raspberry PI
#
# Save this file in /etc/init.d/supervisord
# After save it, exec the commands:
# sudo chmod +x /etc/init.d/supervisord
# sudo update-rc.d supervisord defaults
#
# description: Auto-starts supervisord
# processname: supervisord
# pidfile: /var/run/supervisord.pid
#
# More info in:
# http://serverfault.com/questions/96499/how-to-automatically-start-supervisord-on-linux-ubuntu

SUPERVISORD=/usr/local/bin/supervisord
SUPERVISORCTL=/usr/local/bin/supervisorctl

case $1 in
start)
        echo -n "Starting supervisord: "
        $SUPERVISORD
        $SUPERVISOCTL -c /etc/supervisord.conf start all
        echo
        ;;
stop)
        echo -n "Stopping supervisord: "
        $SUPERVISORCTL shutdown
        echo
        ;;
restart)
        echo -n "Stopping supervisord: "
        $SUPERVISORCTL shutdown
        echo
        echo -n "Starting supervisord: "
        $SUPERVISORD
        $SUPERVISOCTL -c /etc/supervisord.conf start all
        echo
        ;;
esac
